spring:
  thymeleaf:
    mode: HTML5
logging:
  level:
    org:
      springframework: error
    com:
      codedrinker:
        dao: debug
server:
  port: ${port:8888}

# 记得替换成你的id和secret
wechat:
  appid: wx207bf36714907ae2
  secret: 7aaa17bd243ecc39cc14d4984312e009

## h2
#db:
#  url: jdbc:h2:~/jiuask
#  username: sa
#  password: sa
#  driver: org.h2.Driver

# mysql
db:
  url: jdbc:mysql://localhost:3306/newhoteldb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
  username: root
  password: root
  driver: com.mysql.cj.jdbc.Driver